<a href="https://colab.research.google.com/github/hftracker/data-science-bootcamp/blob/main/07_uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Tensorflow
>Strona biblioteki: [https://www.tensorflow.org/](https://www.tensorflow.org/)  
>Dokumentacja: [https://www.tensorflow.org/api_docs](https://www.tensorflow.org/api_docs)  
>
>Szybko rozwijająca się biblioteka do uczenia maszynowego i uczenia głębokiego rozwijana przez Google.
>
>Aby zainstalować bibliotekę tensorflow, użyj polecenia poniżej:
```
pip install tensorflow
```

### Keras
>Strona biblioteki: [https://keras.io/](https://keras.io/)  
>
>Wysokopoziomowy interfejs do budowy sieci neuronowych. Działa zarówno na Tensorflow, Theano oraz CNTK.
>
>Aby zainstalować bibliotekę keras, użyj polecenia poniżej:
```
pip install keras
```

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Załadowanie biblioteki tensorflow


In [2]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.9.2'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [3]:
# utworzenie instancji klasy Sequential
# zmiana - keras już jest osobną klasą

from keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*
parametry:
unit=4 oznacza że chcemy mieć 4 neurony
input_shape - zawsze w pierwszej warstwie, określa ile paramentrów mają dane wejściowe

In [4]:
from keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

Wyświetlenie podsumowania modelu: metoda *.summary()*

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy

In [6]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [7]:
from keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [8]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [9]:
from keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [10]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [11]:
from keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [12]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [13]:
from keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [14]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [15]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/)) 
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [16]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [17]:
data[:3]

array([[-1.24563362,  0.21338287,  1.33322403, -1.37709796,  1.75409874,
        -0.0521724 , -1.33321196,  0.6620389 , -0.18329074,  0.04883552,
         0.76778851,  0.51375916, -0.20173217, -0.4945226 , -0.23320769,
         0.81875846, -1.59126987,  0.27314811, -0.52295535,  1.00822802,
        -0.16569149, -0.06968708, -0.72984885,  0.6220262 ,  3.07039929,
         0.35283543, -0.35165043,  0.30222525, -0.90710945,  0.08107628,
         0.31359191, -0.50289413, -0.42265619,  0.26324502,  0.79156211,
         0.54203635, -1.36755461,  1.57492727,  0.32698028, -0.55644433,
        -0.8312791 ,  0.56283836, -0.32732155,  0.35052468,  0.21708365,
         0.03391944,  1.33399186,  0.74847034,  2.22934513, -1.39780403,
         1.45628967, -0.47894092,  0.2627916 , -0.58120712,  1.32255496,
        -1.10737864, -0.22027753,  1.0451197 , -0.55952543, -1.3661739 ,
         2.13893689,  1.20321359, -0.77266827,  0.20682108, -0.6000789 ,
         1.22627131, -0.70418391, -0.46903132, -1.3

In [18]:
labels[:10]

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [19]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 2s 2ms/step - loss: 0.7463 - accuracy: 0.4969
Epoch 2/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6960 - accuracy: 0.5410
Epoch 3/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6785 - accuracy: 0.5690
Epoch 4/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6642 - accuracy: 0.5950
Epoch 5/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6512 - accuracy: 0.6208
Epoch 6/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6383 - accuracy: 0.6390
Epoch 7/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6243 - accuracy: 0.6569
Epoch 8/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6113 - accuracy: 0.6685
Epoch 9/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5968 - accuracy: 0.6875
Epoch 10/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5839 - accuracy: 0.7000

In [20]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 1s 2ms/step - loss: 0.7535 - accuracy: 0.5016
Epoch 2/20
157/157 [==============================] - 0s 3ms/step - loss: 0.7014 - accuracy: 0.5365
Epoch 3/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6846 - accuracy: 0.5646
Epoch 4/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6728 - accuracy: 0.5855
Epoch 5/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6625 - accuracy: 0.6047
Epoch 6/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6523 - accuracy: 0.6191
Epoch 7/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6423 - accuracy: 0.6337
Epoch 8/20
157/157 [==============================] - 0s 3ms/step - loss: 0.6320 - accuracy: 0.6488
Epoch 9/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6220 - accuracy: 0.6591
Epoch 10/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6116 - accuracy: 0.6709

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/20
8000/8000 [==============================] - 1s 134us/sample - loss: 0.7480 - accuracy: 0.5017 - val_loss: 0.7293 - val_accuracy: 0.4955
Epoch 2/20
8000/8000 [==============================] - 1s 64us/sample - loss: 0.6948 - accuracy: 0.5371 - val_loss: 0.7210 - val_accuracy: 0.5075
Epoch 3/20
8000/8000 [==============================] - 0s 60us/sample - loss: 0.6746 - accuracy: 0.5782 - val_loss: 0.7222 - val_accuracy: 0.5010
Epoch 4/20
8000/8000 [==============================] - 0s 62us/sample - loss: 0.6584 - accuracy: 0.6061 - val_loss: 0.7229 - val_accuracy: 0.5110
Epoch 5/20
8000/8000 [==============================] - 0s 59us/sample - loss: 0.6439 - accuracy: 0.6338 - val_loss: 0.7271 - val_accuracy: 0.5080
Epoch 6/20
8000/8000 [==============================] - 0s 61us/sample - loss: 0.6284 - accuracy: 0.6509 - val_loss: 0.7354 - val_accuracy: 0.5020
Epoch 7/20
8000/8000 [==============================] - 0s 62us/sampl

In [21]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [22]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [30]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 [==============================] - 1s 4ms/step - loss: 0.7608 - accuracy: 0.5059 - val_loss: 0.7309 - val_accuracy: 0.4840
Epoch 2/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6978 - accuracy: 0.5439 - val_loss: 0.7256 - val_accuracy: 0.5035
Epoch 3/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6758 - accuracy: 0.5795 - val_loss: 0.7229 - val_accuracy: 0.5055
Epoch 4/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6598 - accuracy: 0.6021 - val_loss: 0.7292 - val_accuracy: 0.4950
Epoch 5/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6453 - accuracy: 0.6217 - val_loss: 0.7336 - val_accuracy: 0.4990
Epoch 6/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6305 - accuracy: 0.6464 - val_loss: 0.7377 - val_accuracy: 0.5005
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6154 - accuracy: 0.6639 - val_loss: 0.7458 - val_accuracy: 0.5040
Epoch 

In [24]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [31]:
model.predict(test_data)

1/1 [==============================] - 0s 52ms/step


array([[0.9084881 ],
       [0.1626845 ],
       [0.8596353 ],
       [0.7274729 ],
       [0.16890639]], dtype=float32)

In [46]:
# model.predict_proba(test_data)
# nie działa w wyższej wersji , ale nie próbowałem inaczej bo mi niepotrzebne na razie

In [45]:
# model.predict_classes(test_data)
# komenda nie działa - ale działa :

np.rint(model.predict(test_data)).astype(int)
# lub np.round(model.predict(test_data),0).astype(int)

1/1 [==============================] - 0s 19ms/step


array([[1],
       [0],
       [1],
       [1],
       [0]])

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [47]:
data = np.random.random((10000, 150))             # 10000 próbek po 150 losowych danych
labels = np.random.randint(10, size=(10000, 1))   # 10000 labels losowo w przedziale od 0-9

In [53]:
print(data.shape)
print(labels.shape)
type(data[:1])
data[:1]

(10000, 150)
(10000, 1)


array([[0.88964464, 0.30508879, 0.71211907, 0.50383223, 0.71461814,
        0.64197506, 0.91133545, 0.62035313, 0.26110911, 0.03770896,
        0.83228008, 0.96012819, 0.87037608, 0.48837466, 0.67804038,
        0.86193067, 0.77717503, 0.28976438, 0.92905483, 0.70093621,
        0.18182199, 0.47339246, 0.42011081, 0.17866363, 0.05722982,
        0.51426772, 0.06030952, 0.48379136, 0.25382487, 0.41288333,
        0.2866025 , 0.57529824, 0.90101839, 0.41485834, 0.80089932,
        0.99994685, 0.06718526, 0.03643664, 0.46260052, 0.04030528,
        0.38893231, 0.38387054, 0.07085331, 0.49280148, 0.46858919,
        0.38963978, 0.77919301, 0.80216167, 0.4938876 , 0.95958321,
        0.48433669, 0.20963137, 0.26416323, 0.95837728, 0.8705417 ,
        0.70088237, 0.45516743, 0.10866726, 0.43670104, 0.88281854,
        0.7013469 , 0.91180105, 0.9779301 , 0.40670987, 0.58760217,
        0.10933715, 0.60739231, 0.2846812 , 0.18261343, 0.83065581,
        0.24290038, 0.58808482, 0.55441691, 0.83

In [56]:
labels[:10]

array([[4],
       [1],
       [4],
       [0],
       [6],
       [8],
       [5],
       [9],
       [9],
       [2]])

In [ ]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
labels[1]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/30
8000/8000 [==============================] - 1s 140us/sample - loss: 2.3235 - accuracy: 0.0980 - val_loss: 2.3153 - val_accuracy: 0.0985
Epoch 2/30
8000/8000 [==============================] - 0s 60us/sample - loss: 2.3052 - accuracy: 0.1047 - val_loss: 2.3040 - val_accuracy: 0.0995
Epoch 3/30
8000/8000 [==============================] - 1s 63us/sample - loss: 2.3031 - accuracy: 0.1009 - val_loss: 2.3104 - val_accuracy: 0.1090
Epoch 4/30
8000/8000 [==============================] - 1s 63us/sample - loss: 2.3016 - accuracy: 0.1039 - val_loss: 2.3061 - val_accuracy: 0.1065
Epoch 5/30
8000/8000 [==============================] - 0s 60us/sample - loss: 2.3005 - accuracy: 0.1155 - val_loss: 2.3084 - val_accuracy: 0.0990
Epoch 6/30
8000/8000 [==============================] - 0s 61us/sample - loss: 2.2979 - accuracy: 0.1119 - val_loss: 2.3134 - val_accuracy: 0.0985
Epoch 7/30
8000/8000 [==============================] - 0s 62us/sampl

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.09911948, 0.11620636, 0.07320527, 0.15997937, 0.08313195,
        0.11985189, 0.07282171, 0.08499081, 0.09132902, 0.09936419],
       [0.10808039, 0.11060798, 0.1585828 , 0.04076305, 0.11867085,
        0.11622953, 0.10032436, 0.10682581, 0.06562724, 0.07428803],
       [0.0535747 , 0.0826021 , 0.15126106, 0.04798588, 0.03644897,
        0.08196826, 0.17952028, 0.07557219, 0.14473361, 0.14633295],
       [0.12001421, 0.15575112, 0.13602467, 0.08515704, 0.06826283,
        0.06773269, 0.0736742 , 0.08663882, 0.09184736, 0.11489701],
       [0.1503428 , 0.14404033, 0.20681618, 0.0435313 , 0.07448085,
        0.05074822, 0.06210018, 0.0954838 , 0.08630197, 0.08615443],
       [0.09830751, 0.07327876, 0.17003337, 0.14070372, 0.07893839,
        0.0776796 , 0.12669246, 0.09419221, 0.07801841, 0.06215557],
       [0.05894386, 0.06890954, 0.10082155, 0.08828751, 0.06637203,
        0.16312268, 0.15596974, 0.08681998, 0.09833211, 0.11242106],
       [0.07287443, 0.06215156, 0.2424068

In [ ]:
model.predict_classes(test_data)

array([3, 2, 6, 1, 2, 2, 5, 2, 4, 2])

### <a name='a6'></a> Przykład - regresja

In [ ]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [ ]:
labels[:10]

array([ 2.76589765, 26.25951681, 42.46470588, 33.45842006,  6.10047945,
       42.16472461,  0.06071142,  9.63306066,  7.97318495, 49.39214105])

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/30
8000/8000 [==============================] - 1s 99us/sample - loss: 269.9293 - val_loss: 207.3698
Epoch 2/30
8000/8000 [==============================] - 0s 60us/sample - loss: 208.6766 - val_loss: 207.3182
Epoch 3/30
8000/8000 [==============================] - 0s 57us/sample - loss: 208.1491 - val_loss: 208.2676
Epoch 4/30
8000/8000 [==============================] - 0s 58us/sample - loss: 207.8588 - val_loss: 207.4424
Epoch 5/30
8000/8000 [==============================] - 0s 58us/sample - loss: 207.5430 - val_loss: 207.8541
Epoch 6/30
8000/8000 [==============================] - 0s 58us/sample - loss: 207.2514 - val_loss: 209.6800
Epoch 7/30
8000/8000 [==============================] - 0s 60us/sample - loss: 206.8425 - val_loss: 208.7884
Epoch 8/30
8000/8000 [==============================] - 0s 59us/sample - loss: 206.7675 - val_loss: 207.5888
Epoch 9/30
8000/8000 [==============================] - 0s 58us/sample - loss: 2

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/10
8000/8000 [==============================] - 1s 107us/sample - loss: 13.3688 - mse: 250.6315 - val_loss: 12.4057 - val_mse: 207.8904
Epoch 2/10
8000/8000 [==============================] - 0s 58us/sample - loss: 12.4745 - mse: 209.1429 - val_loss: 12.4120 - val_mse: 208.6593
Epoch 3/10
8000/8000 [==============================] - 1s 64us/sample - loss: 12.4606 - mse: 208.5854 - val_loss: 12.3944 - val_mse: 207.4827
Epoch 4/10
8000/8000 [==============================] - 0s 58us/sample - loss: 12.4351 - mse: 208.3050 - val_loss: 12.4262 - val_mse: 209.8297
Epoch 5/10
8000/8000 [==============================] - 0s 58us/sample - loss: 12.4279 - mse: 207.8135 - val_loss: 12.4113 - val_mse: 208.1427
Epoch 6/10
8000/8000 [==============================] - 0s 59us/sample - loss: 12.4111 - mse: 207.7288 - val_loss: 12.4030 - val_mse: 207.9031
Epoch 7/10
8000/8000 [==============================] - 0s 62us/sample - loss: 12.3957 - mse:

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[25.318836],
       [25.124805],
       [26.249212],
       [26.726828],
       [24.240023],
       [26.99018 ],
       [22.903202],
       [25.071842],
       [22.852095],
       [25.543777]], dtype=float32)