<a href="https://colab.research.google.com/github/hftracker/data-science-bootcamp/blob/main/07_uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Tensorflow
>Strona biblioteki: [https://www.tensorflow.org/](https://www.tensorflow.org/)  
>Dokumentacja: [https://www.tensorflow.org/api_docs](https://www.tensorflow.org/api_docs)  
>
>Szybko rozwijająca się biblioteka do uczenia maszynowego i uczenia głębokiego rozwijana przez Google.
>
>Aby zainstalować bibliotekę tensorflow, użyj polecenia poniżej:
```
pip install tensorflow
```

### Keras
>Strona biblioteki: [https://keras.io/](https://keras.io/)  
>
>Wysokopoziomowy interfejs do budowy sieci neuronowych. Działa zarówno na Tensorflow, Theano oraz CNTK.
>
>Aby zainstalować bibliotekę keras, użyj polecenia poniżej:
```
pip install keras
```

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Załadowanie biblioteki tensorflow


In [2]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.9.2'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [3]:
# utworzenie instancji klasy Sequential
# zmiana - keras już jest osobną klasą

from keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*
parametry:
unit=4 oznacza że chcemy mieć 4 neurony
input_shape - zawsze w pierwszej warstwie, określa ile paramentrów mają dane wejściowe

In [4]:
from keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

Wyświetlenie podsumowania modelu: metoda *.summary()*

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy

In [6]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [7]:
from keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [8]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [9]:
from keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [10]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [11]:
from keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [12]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [13]:
from keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [14]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [15]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/)) 
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [16]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [17]:
data[:3]

array([[-1.24563362,  0.21338287,  1.33322403, -1.37709796,  1.75409874,
        -0.0521724 , -1.33321196,  0.6620389 , -0.18329074,  0.04883552,
         0.76778851,  0.51375916, -0.20173217, -0.4945226 , -0.23320769,
         0.81875846, -1.59126987,  0.27314811, -0.52295535,  1.00822802,
        -0.16569149, -0.06968708, -0.72984885,  0.6220262 ,  3.07039929,
         0.35283543, -0.35165043,  0.30222525, -0.90710945,  0.08107628,
         0.31359191, -0.50289413, -0.42265619,  0.26324502,  0.79156211,
         0.54203635, -1.36755461,  1.57492727,  0.32698028, -0.55644433,
        -0.8312791 ,  0.56283836, -0.32732155,  0.35052468,  0.21708365,
         0.03391944,  1.33399186,  0.74847034,  2.22934513, -1.39780403,
         1.45628967, -0.47894092,  0.2627916 , -0.58120712,  1.32255496,
        -1.10737864, -0.22027753,  1.0451197 , -0.55952543, -1.3661739 ,
         2.13893689,  1.20321359, -0.77266827,  0.20682108, -0.6000789 ,
         1.22627131, -0.70418391, -0.46903132, -1.3

In [18]:
labels[:10]

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [19]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 2s 2ms/step - loss: 0.7463 - accuracy: 0.4969
Epoch 2/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6960 - accuracy: 0.5410
Epoch 3/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6785 - accuracy: 0.5690
Epoch 4/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6642 - accuracy: 0.5950
Epoch 5/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6512 - accuracy: 0.6208
Epoch 6/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6383 - accuracy: 0.6390
Epoch 7/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6243 - accuracy: 0.6569
Epoch 8/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6113 - accuracy: 0.6685
Epoch 9/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5968 - accuracy: 0.6875
Epoch 10/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5839 - accuracy: 0.7000

In [20]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 1s 2ms/step - loss: 0.7535 - accuracy: 0.5016
Epoch 2/20
157/157 [==============================] - 0s 3ms/step - loss: 0.7014 - accuracy: 0.5365
Epoch 3/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6846 - accuracy: 0.5646
Epoch 4/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6728 - accuracy: 0.5855
Epoch 5/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6625 - accuracy: 0.6047
Epoch 6/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6523 - accuracy: 0.6191
Epoch 7/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6423 - accuracy: 0.6337
Epoch 8/20
157/157 [==============================] - 0s 3ms/step - loss: 0.6320 - accuracy: 0.6488
Epoch 9/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6220 - accuracy: 0.6591
Epoch 10/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6116 - accuracy: 0.6709

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/20
8000/8000 [==============================] - 1s 134us/sample - loss: 0.7480 - accuracy: 0.5017 - val_loss: 0.7293 - val_accuracy: 0.4955
Epoch 2/20
8000/8000 [==============================] - 1s 64us/sample - loss: 0.6948 - accuracy: 0.5371 - val_loss: 0.7210 - val_accuracy: 0.5075
Epoch 3/20
8000/8000 [==============================] - 0s 60us/sample - loss: 0.6746 - accuracy: 0.5782 - val_loss: 0.7222 - val_accuracy: 0.5010
Epoch 4/20
8000/8000 [==============================] - 0s 62us/sample - loss: 0.6584 - accuracy: 0.6061 - val_loss: 0.7229 - val_accuracy: 0.5110
Epoch 5/20
8000/8000 [==============================] - 0s 59us/sample - loss: 0.6439 - accuracy: 0.6338 - val_loss: 0.7271 - val_accuracy: 0.5080
Epoch 6/20
8000/8000 [==============================] - 0s 61us/sample - loss: 0.6284 - accuracy: 0.6509 - val_loss: 0.7354 - val_accuracy: 0.5020
Epoch 7/20
8000/8000 [==============================] - 0s 62us/sampl

In [21]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [22]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [30]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 [==============================] - 1s 4ms/step - loss: 0.7608 - accuracy: 0.5059 - val_loss: 0.7309 - val_accuracy: 0.4840
Epoch 2/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6978 - accuracy: 0.5439 - val_loss: 0.7256 - val_accuracy: 0.5035
Epoch 3/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6758 - accuracy: 0.5795 - val_loss: 0.7229 - val_accuracy: 0.5055
Epoch 4/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6598 - accuracy: 0.6021 - val_loss: 0.7292 - val_accuracy: 0.4950
Epoch 5/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6453 - accuracy: 0.6217 - val_loss: 0.7336 - val_accuracy: 0.4990
Epoch 6/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6305 - accuracy: 0.6464 - val_loss: 0.7377 - val_accuracy: 0.5005
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6154 - accuracy: 0.6639 - val_loss: 0.7458 - val_accuracy: 0.5040
Epoch 

In [24]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [31]:
model.predict(test_data)

1/1 [==============================] - 0s 52ms/step


array([[0.9084881 ],
       [0.1626845 ],
       [0.8596353 ],
       [0.7274729 ],
       [0.16890639]], dtype=float32)

In [46]:
# model.predict_proba(test_data)
# nie działa w wyższej wersji , ale nie próbowałem inaczej bo mi niepotrzebne na razie

In [45]:
# model.predict_classes(test_data)
# komenda nie działa - ale działa :

np.rint(model.predict(test_data)).astype(int)
# lub np.round(model.predict(test_data),0).astype(int)

1/1 [==============================] - 0s 19ms/step


array([[1],
       [0],
       [1],
       [1],
       [0]])

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [47]:
data = np.random.random((10000, 150))             # 10000 próbek po 150 losowych danych
labels = np.random.randint(10, size=(10000, 1))   # 10000 labels losowo w przedziale od 0-9

In [ ]:
print(data.shape)
print(labels.shape)
type(data[:1])
data[:1]

In [56]:
labels[:10]

array([[4],
       [1],
       [4],
       [0],
       [6],
       [8],
       [5],
       [9],
       [9],
       [2]])

In [58]:
# konwerstujemy labels do większej macierzy która na poz numer x ma 1 (prawdopodobieństwo)

from keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [59]:
labels[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [60]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 3ms/step - loss: 2.3244 - accuracy: 0.1001 - val_loss: 2.3055 - val_accuracy: 0.1030
Epoch 2/30
250/250 [==============================] - 1s 3ms/step - loss: 2.3047 - accuracy: 0.1011 - val_loss: 2.3058 - val_accuracy: 0.0905
Epoch 3/30
250/250 [==============================] - 1s 3ms/step - loss: 2.3016 - accuracy: 0.1107 - val_loss: 2.3064 - val_accuracy: 0.1035
Epoch 4/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2997 - accuracy: 0.1157 - val_loss: 2.3050 - val_accuracy: 0.1085
Epoch 5/30
250/250 [==============================] - 1s 3ms/step - loss: 2.2970 - accuracy: 0.1171 - val_loss: 2.3094 - val_accuracy: 0.1120
Epoch 6/30
250/250 [==============================] - 1s 3ms/step - loss: 2.2943 - accuracy: 0.1179 - val_loss: 2.3068 - val_accuracy: 0.1065
Epoch 7/30
250/250 [==============================] - 1s 3ms/step - loss: 2.2922 - accuracy: 0.1215 - val_loss: 2.3110 - val_accuracy: 0.1035
Epoch 

In [61]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 55ms/step


array([[0.07901973, 0.16803652, 0.08994259, 0.09998217, 0.06214454,
        0.11307044, 0.07062397, 0.04976765, 0.18587583, 0.08153661],
       [0.06635205, 0.0989851 , 0.07950137, 0.08420285, 0.07009164,
        0.0934343 , 0.17475916, 0.12454107, 0.07093308, 0.13719942],
       [0.07686722, 0.10776553, 0.12142429, 0.10280292, 0.10671468,
        0.08700764, 0.09606516, 0.15824561, 0.09518167, 0.04792534],
       [0.09727935, 0.14946264, 0.10778375, 0.08222443, 0.06942093,
        0.10050957, 0.08248658, 0.08237325, 0.14358939, 0.08487011],
       [0.08287625, 0.08493339, 0.10036354, 0.06758931, 0.14512035,
        0.09920795, 0.09321136, 0.06319648, 0.14640579, 0.11709559],
       [0.0945629 , 0.08180064, 0.12327518, 0.10441943, 0.11679829,
        0.08367193, 0.09003624, 0.09263082, 0.09577437, 0.1170302 ],
       [0.10237268, 0.06105652, 0.10784662, 0.06730687, 0.18628238,
        0.09599524, 0.11459725, 0.12395332, 0.07853252, 0.06205659],
       [0.08805781, 0.15922855, 0.0792656

In [62]:
# model.predict_classes(test_data) # nie działa, ale działa poniższe

np.argmax(model.predict(test_data),axis=1)

1/1 [==============================] - 0s 22ms/step


array([8, 6, 7, 1, 8, 2, 4, 1, 1, 4])

### <a name='a6'></a> Przykład - regresja

In [63]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [64]:
labels[:10]

array([ 2.81067188, 24.09220873,  6.40438472, 45.28779591, 23.80988878,
        1.72339317,  6.85291557, 12.998597  , 25.81616054, 41.41914172])

brak funkcji aktywacji oznacza, że jest to domyślna funkcja, czyli liniowa

In [65]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 3ms/step - loss: 272.3183 - val_loss: 218.5812
Epoch 2/30
250/250 [==============================] - 1s 2ms/step - loss: 209.7384 - val_loss: 219.8536
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 209.4407 - val_loss: 218.4885
Epoch 4/30
250/250 [==============================] - 1s 3ms/step - loss: 209.0224 - val_loss: 218.6886
Epoch 5/30
250/250 [==============================] - 1s 3ms/step - loss: 208.9644 - val_loss: 218.5137
Epoch 6/30
250/250 [==============================] - 1s 3ms/step - loss: 208.4603 - val_loss: 218.5457
Epoch 7/30
250/250 [==============================] - 1s 3ms/step - loss: 208.1445 - val_loss: 219.0479
Epoch 8/30
250/250 [==============================] - 1s 2ms/step - loss: 207.9210 - val_loss: 218.6106
Epoch 9/30
250/250 [==============================] - 1s 2ms/step - loss: 207.8715 - val_loss: 219.1138
Epoch 10/30
250/250 [==============================] - 1s 3ms/st

In [66]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 [==============================] - 2s 4ms/step - loss: 13.7519 - mse: 271.4330 - val_loss: 12.8688 - val_mse: 219.6565
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 12.4954 - mse: 210.4631 - val_loss: 12.8403 - val_mse: 218.5496
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 12.4799 - mse: 210.0244 - val_loss: 12.8358 - val_mse: 218.3925
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 12.4543 - mse: 209.5512 - val_loss: 12.8808 - val_mse: 220.0263
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 12.4484 - mse: 209.4624 - val_loss: 12.8429 - val_mse: 218.5929
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 12.4383 - mse: 209.1009 - val_loss: 12.8636 - val_mse: 220.3030
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 12.4241 - mse: 208.8167 - val_loss: 12.8457 - val_mse: 218.7805
Epoch 8/10
250/250 [==============

In [67]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 68ms/step


array([[26.195   ],
       [28.136204],
       [27.824837],
       [24.083609],
       [28.36409 ],
       [23.403572],
       [27.052961],
       [26.700766],
       [23.393576],
       [28.110538]], dtype=float32)